name: Generate Metrics

on:
  schedule:
    # This tells the robot to run every 6 hours
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Setup Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.TOKEN_GITHUB }}
          base: repositories
          plugin_activity: yes
          plugin_stars: yes
          plugin_lines: yes
          plugin_traffic: yes
          output: github-metrics.svg
